spring.application.name=ErrorTicketManager
server.address=0.0.0.0
server.port=8081

# Driver class name (optional, Spring Boot auto-detects this)
spring.datasource.driver-class-name=org.postgresql.Driver