# Database connection settings
jakarta.persistence.jdbc.url=postgresql://localhost:5432
jakarta.persistence.jdbc.user=sa
jakarta.persistence.jdbc.pass=EXAMPLE

# Echo all executed SQL to console
hibernate.show_sql=true
hibernate.format_sql=true
hibernate.highlight_sql=true